/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as KeyvaultRouteImport } from './routes/keyvault'
import { Route as DeletedSecretsRouteImport } from './routes/deleted-secrets'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyvaultRoute = KeyvaultRouteImport.update({
  id: '/keyvault',
  path: '/keyvault',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletedSecretsRoute = DeletedSecretsRouteImport.update({
  id: '/deleted-secrets',
  path: '/deleted-secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/deleted-secrets': typeof DeletedSecretsRoute
  '/keyvault': typeof KeyvaultRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/deleted-secrets': typeof DeletedSecretsRoute
  '/keyvault': typeof KeyvaultRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/deleted-secrets': typeof DeletedSecretsRoute
  '/keyvault': typeof KeyvaultRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/deleted-secrets'
    | '/keyvault'
    | '/search'
    | '/settings'
    | '/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/deleted-secrets'
    | '/keyvault'
    | '/search'
    | '/settings'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/deleted-secrets'
    | '/keyvault'
    | '/search'
    | '/settings'
    | '/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DeletedSecretsRoute: typeof DeletedSecretsRoute
  KeyvaultRoute: typeof KeyvaultRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyvault': {
      id: '/keyvault'
      path: '/keyvault'
      fullPath: '/keyvault'
      preLoaderRoute: typeof KeyvaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deleted-secrets': {
      id: '/deleted-secrets'
      path: '/deleted-secrets'
      fullPath: '/deleted-secrets'
      preLoaderRoute: typeof DeletedSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DeletedSecretsRoute: DeletedSecretsRoute,
  KeyvaultRoute: KeyvaultRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
